### ISSUE TITLE
 Triac in heater circuit may be overloaded

### ISSUE THREAD

**Issue by VaRe123** [MadPresso/Hardware#1]
Check carefully figure 3 of the datasheet of triac T835-600G:

![image](https://user-images.githubusercontent.com/63047432/106402514-1d6cb680-642a-11eb-972e-1fe94a572847.png)

When heating up you can't use the full 1150W of the heater as this would be equivalent to approx. 5 A RMS current! The D2PAK package in use is only capable of conducting 3 A RMS at max, even it is different stated in the header of the datasheet (8A RMS).

**Comment by zonque** [comment]
Ah, thanks for spotting this! I've changed the Triac type to the one that was actually used during development (BT138-600).

**Comment by VaRe123** [comment]
Do you use a heatsink then on this specific triac?

**Comment by zonque** [comment]
Fischer ICK24B can be glued across on all 3 Triacs, yes. But as heat is dissipated well enough through the PCB, my measurements so far show only temperatures below 90°C on the package surface.
